name: Release Deploy

on:
  push:
    branches: [release]

jobs:
  pipeline:
    uses: beamo-solutions/proxmox-homelab-integration/.github/workflows/reusable-full-pipeline.yml@main
    with:
      app_name: deskhubpilot
      dockerfile: ./Dockerfile
    secrets: inherit
